# Generated by Django 4.2.17 on 2024-12-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_for_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default="12345", max_length=5),
            preserve_default=False,
        ),
    ]
