# Generated by Django 4.2.17 on 2024-12-11 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='invited',
        ),
        migrations.AddField(
            model_name='referral',
            name='invited',
            field=models.ManyToManyField(related_name='ref_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
